### ISSUE TITLE
Mounting check.d folder as volume deletes all check files on host

### ISSUE THREAD

**Issue by ismarslomic** [sstarcher/docker-sensu#29]
Sensu **Client** compose-file looks like this:

```
version: '2'
services:
  client:
    command: client
    container_name: docker-sensu-client-prod
    image: sstarcher/sensu
    environment:
      CLIENT_NAME: testclient
      CLIENT_SUBSCRIPTIONS: os
      CLIENT_ADDRESS: 127.0.0.1
      RUNTIME_INSTALL: docker memory-checks
      REDIS_HOST: 192.168.99.100
      REDIS_PORT: 6379
      #REDIS_PASSWORD: ""
      #REDIS_DB: 0
      REDIS_AUTO_RECONNECT: "true"
      REDIS_RECONNECT_ON_ERROR: "true"
    volumes:
      - ./resources/check.d:/etc/sensu/check.d/
    ports:
      - '3030:3030'
```

Same place as the compose-file is placed I have folder named `resources` which contains `check.d` folder where all check files are placed. After running `docker-compose up -d` all files within ./resource/check.d are deleted.
