### ISSUE TITLE
How to verify if checks are executed on host machine and not docker container?

### ISSUE THREAD

**Issue by ismarslomic** [sstarcher/docker-sensu#30]
I would like to verify/test that all checks are running on host machine and not within the docker container where Sensu client is running. Could you please help out with some hints? My docker-compose file looks like this:

```
version: '2'
services:
  client:
    build: .
    command: client
    container_name: docker-sensu-client-prod
    image: adop/sensu-client
    environment:
      CLIENT_NAME: aca-jira01
      CLIENT_SUBSCRIPTIONS: basic
      CLIENT_ADDRESS: 127.0.0.1
      REDIS_HOST: 192.168.99.100
      REDIS_PORT: 6379
      REDIS_AUTO_RECONNECT: "true"
      REDIS_RECONNECT_ON_ERROR: "true"
      HOST_DEV_DIR: /host_dev
      HOST_PROC_DIR: /host_proc
      HOST_SYS_DIR: /host_sys
    ports:
      - '3030:3030'
    volumes:
      - /dev:/host_dev/:ro
      - /proc:/host_proc/:ro
      - /sys:/host_sys/:ro
```
