### ISSUE TITLE
Sensu Client doesn't start

### ISSUE THREAD

**Issue by Northwood128** [sstarcher/docker-sensu#48]
Howdy!!

I'm trying to create a Sensu Stack in order to have a quick way to instantiate a development stage for Sensu related tools. I found your image very convenient. However I'm having some issues starting the sensu client container.

This is my docker-compose.yml
```
  version: "3"
  services:
      rabbitmq:
          image: rabbitmq:3.6-management-alpine
          ports:
              - 15672:15672
          environment:
              RABBITMQ_HIPE_COMPILE: 1
              RABBITMQ_ERLANG_COOKIE: 'sarasa'
          networks:
             - my-net
      server:
          image: sstarcher/sensu
          command: server
          links:
              - api
              - rabbitmq
              - redis
          volumes:
              - "./server-conf/server.json:/etc/sensu/config.json"
              - "./logs:/var/log/sensu/"
          networks:
             - my-net
      api:
          image: sstarcher/sensu
          command: api
          links:
              - redis
          ports:
              - '4567:4567'
          volumes:
              - "./api-conf/api.json:/etc/sensu/config.json"
              - "./logs:/var/log/sensu/"
          networks:
             - my-net
      client:
          image: sstarcher/sensu
          command: client
          links:
              - rabbitmq
          volumes:
              - "/dev:/host_dev/:ro"
              - "/proc:/host_proc/:ro"
              - "/sys:/host_sys/:ro"
              - "./client-conf/client.json:/etc/sensu/config.json"
              - "./logs:/var/log/sensu/"
          environment:
              HOST_DEV_DIR: /host_dev
              HOST_PROC_DIR: /host_proc
              HOST_SYS_DIR: /host_sys
          networks:
             - my-net
      uchiwa:
          image: sstarcher/uchiwa
          links:
              - api
          ports:
              - '3000:3000'
          volumes:
              - "./dashboard:/etc/sensu/dashboard.d"
              - "./logs/uchiwa.log:/var/log/uchiwa.log"
          networks:
             - my-net
      redis:
          image: redis:3
          networks:
             - my-net
  networks:
      my-net:
```
All of the containers start just fine but the one for the client. Is shows this message:

```
{"timestamp":"2017-06-16T20:37:18.101670+0000","level":"warn","message":"loading config file","file":"/etc/sensu/config.json"}
{"timestamp":"2017-06-16T20:37:18.102094+0000","level":"warn","message":"loading config files from directory","directory":"/etc/sensu/conf.d"}
{"timestamp":"2017-06-16T20:37:18.102367+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/transport.json"}
{"timestamp":"2017-06-16T20:37:18.102640+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/transport.json","changes":{}}
{"timestamp":"2017-06-16T20:37:18.102879+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/client.json"}
{"timestamp":"2017-06-16T20:37:18.102981+0000","level":"fatal","message":"config file must be valid json","file":"/etc/sensu/conf.d/client.json","error":"unexpected comma at line 7, column 17 [parse.c:575]"}
{"timestamp":"2017-06-16T20:37:18.103128+0000","level":"fatal","message":"SENSU NOT RUNNING!"}
```

./client-conf/client.json looks like: 
```
{
  "client": {
    "socket": {
      "bind": "127.0.0.1"
    },
    "name": "4494446b45e0",
    "address": "127.0.0.1",
    "subscriptions": [
        "docker"
    ],
    "keepalive": {
      "thresholds": {
         "warning": 120,
         "critical": 180
      },
      "handler": "default"
    }
  },
  "transport": {
    "name": "redis",
    "reconnect_on_error": true
  },
  "rabbitmq": {
    "host": "rabbitmq",
    "port": 5671,
    "vhost": "/sensu",
    "user": "sensu",
    "password": "secret",
    "heartbeat": 30,
    "prefetch": 50
  }
}
```
I don't know where it gets that /etc/sensu/conf.d/* config files. Can you lend me a hand?
Thanks in advance!
